### ISSUE TITLE
Identifying clients

### ISSUE THREAD

**Issue by DavidVentura** [daktak/androidpn-client#20]
Although I can search for myself in the list by 'username', is there any way to register yourself(name,mail) from the client?

**Comment by daktak** [comment]
Not currently. 
I'll put it on the to do list

**Comment by daktak** [comment]
#21 allows you to specify email and display name.

**Comment by DavidVentura** [comment]
It's fixed on the merge of #21. Do you also maintain the server? Do you know if anyone actually maintains it? I just modified the launch script and added a systemd service file and I'd like to upload it
